version: '3'
services:
  app:
    container_name: omm
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - ./:/usr/src/app:rw,cached
      - /usr/src/app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'